[config]
schemaVersion = "0.0.1"

[package]
namespace = "AuthorName"
name = "PackageName"
versionNumber = "0.0.1"
description = "Simple Valheim vanilla + modpack made for me and a few friends. Mostly QOL features and a few extra additions."
websiteUrl = ""
containsNsfwContent = false

[package.dependencies]
AuthorName-PackageName = "0.0.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]
[publish.categories]
valheim = [ "modpacks" ]


