[config]
schemaVersion = "0.0.1"

[package]
namespace = "DealBreackers_Assembly"
name = "DealBreackers_Haven_Assembly"
versionNumber = "1.0.3"
description = "Example mod description"
websiteUrl = "https://thunderstore.io"
containsNsfwContent = false
[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2202"
Advize-PlantEverything = "1.19.1"
Vapok-AdventureBackpacks = "1.7.10"
ValheimModding-Jotunn = "2.24.3"
ValheimModding-HookGenPatcher = "0.0.4"
MathiasDecrock-PlanBuild = "0.18.2"
Smoothbrain-Vitality = "1.1.2"
do_the_dew-VitalityFix = "0.0.7"
virtuaCode-EquipWheel = "1.5.3"
RandyKnapp-EquipmentAndQuickSlots = "2.1.14"
blacks7ar-LazyVikings = "1.2.0"
Therzie-Warfare = "1.8.9"
0zz-SeedTotem = "0.1.3"
ishid4-BetterArchery = "1.9.81"
MSchmoecker-MultiUserChest = "0.6.1"
blacks7ar-VikingsDoSwim = "1.3.8"
N3xus-FarmGrid = "0.2.0"
Smoothbrain-Mining = "1.1.5"
Smoothbrain-Sailing = "1.1.7"
Tekla-AutoRepair = "5.4.1602"
Smoothbrain-Lumberjacking = "1.0.5"
mgway-PaddlePower = "1.0.2"
Smoothbrain-Building = "1.2.5"
virtuaCode-EmoteWheel = "1.4.1"
Smoothbrain-Foraging = "1.0.9"
Smoothbrain-Tenacity = "1.0.3"
Smoothbrain-Evasion = "1.0.3"
Smoothbrain-Ranching = "1.1.3"
Smoothbrain-PackHorse = "1.0.3"
Smoothbrain-SmartSkills = "1.0.2"
Advize-CartographySkill = "3.0.1"
MaxFoxGaming-Better_Beehives = "1.2.3"
blacks7ar-BeeKeeper = "1.0.6"
HS-HS_EquipInWater = "1.0.0"
Smoothbrain-Network = "1.0.2"
valheimgc-BetterArcheryEAQSFix = "0.0.1"
blacks7ar-WieldEquipmentWhileSwimming = "1.1.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]
[publish.categories]
valheim = [ "modpacks" ]


