[config]
schemaVersion = "0.0.1"  # Leave this unchanged

[package]
namespace = "YourAuthorName"    # Must match your Thunderstore account
name = "YourModName"            # Display name (no spaces/special chars)
versionNumber = "1.0.0"         # Semantic versioning (major.minor.patch)
description = "Your mod's functionality description"
websiteUrl = "https://github.com/your-repo"  # Or Thunderstore profile URL
containsNsfwContent = false     # Set true if mature content

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"  # Core dependency example
RiskofThunder-R2API = "4.4.1"      # API dependency example

[build]
icon = "./icon.png"        # 256x256 PNG
readme = "./README.md"     # Markdown with installation/usage info
outdir = "./build"         # Output directory for built package

[[build.copy]]             # Files to include in package
source = "./dist"          # Your compiled mod files
target = ""                # Installs to mod root directory

[publish]
repository = "https://thunderstore.io"
communities = ["riskofrain2"]  # Game identifier

[publish.categories]
riskofrain2 = ["gameplay"]  # Valid categories: gameplay, characters, items, 
                           # skins, utilities, audio, libraries

